# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-17 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanish_content', '0013_auto_20170314_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduprogram',
            name='video',
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='row_style',
            field=models.CharField(choices=[(b'full', b'Full Row'), (b'highlight', b'Highlight'), (b'long_short', b'Long Short'), (b'short_long', b'Short Long')], default=b'full', max_length=15),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='email_signup',
            field=models.TextField(blank=True, help_text=b'you can enter code here for an email signup', null=True),
        ),
    ]
