# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_footerinfo_email_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.TextField(help_text='Enter the Google Analytics event snippet here for the page indicated')),
                ('page', models.CharField(choices=[('AboutUs', 'AboutUs'), ('Donate', 'Donate'), ('Club', 'Club'), ('Paypal', 'Paypal'), ('Global', 'Global')], default='AboutUs', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
