# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_auto_20181009_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytictag',
            name='page',
            field=models.CharField(choices=[('ourstory', 'ourstory'), ('peru', 'peru'), ('ethics', 'ethics'), ('financials', 'financials'), ('ourteam', 'ourteam'), ('teensprogram', 'teensprogram'), ('childrensprogram', 'childrensprogram'), ('womensprogram', 'womensprogram'), ('donate', 'donate'), ('volunteerperu', 'volunteerperu'), ('chicago', 'chicago'), ('donations', 'donations'), ('Global', 'Global')], default='ourstory', max_length=15),
        ),
    ]
